{"A",  "<algoritmo>", "<str>", "LISTADECLAR", "<inicio>", "CODIGO", "<fimalgoritmo>", "/e/"},
{"LISTADECLAR",  "UNIDECLAR", "LISTADECLAR"},
{"LISTADECLAR",  "MULTIDECLAR", "LISTADECLAR"},
{"LISTADECLAR",  "/e/"},
{"UNIDECLAR",  "<var>", "<id>", "<del|:>", "TIPO"},
{"MULTIDECLAR",  "IDLIST", "<del|:>", "TIPO"},
{"TIPO",  "<inteiro>"},
{"TIPO",  "<logico>"},
{"IDLIST",  "<id>", "IDLIST"},
{"IDLIST",  "<del|,>", "<id>", "IDLIST"},
{"IDLIST",  "/e/"},
{"CODIGO",  "COMANDO", "CODIGO"},
{"CODIGO",  "/e/"},
{"COMANDO",  "<id>", "<op|<->", "EXPRESSAO"},
{"COMANDO",  "<leia>", "<del|(>", "IDLIST", "<del|)>"},
{"COMANDO",  "<escreva>", "<del|(>", "STROUT", "<del|)>"},
{"COMANDO",  "<se>", "EXPRESSAOLOGICA", "<entao>", "CODIGO", "<senao>", "CODIGO", "<fimse>", "/e/"},
{"COMANDO",  "<se>", "EXPRESSAOLOGICA", "<entao>", "CODIGO", "SENAO", "<fimse>", "/e/"},
{"COMANDO",  "<para>", "<id>", "<de>", "<num>", "<ate>", "<num>", "PASSO", "<faca>", "CODIGO", "<fimpara>", "/e/"},
{"COMANDO",  "<enquanto>", "EXPRESSAOLOGICA", "<faca>", "CODIGO", "<fimenquanto>", "/e/"},
{"SENAO",  "<senao>", "CODIGO"},
{"SENAO",  "/e/"},
{"PASSO",  "<passo>", "<num>"},
{"PASSO",  "/e/"},
{"EXPRESSAO",  "DATA", "OPERANDO"},
{"OPERANDO",  "OP", "DATA"},
{"OPERANDO",  "/e/"},
{"STROUT",  "PRINTABLE", "STROUT"},
{"STROUT",  "<del|,>", "PRINTABLE", "STROUT"},
{"STROUT",  "/e/"},
{"PRINTABLE",  "<id>"},
{"PRINTABLE",  "<str>"},
{"EXPRESSAOLOGICA",  "DATA", "EXPRESSAOLOGICA"},
{"EXPRESSAOLOGICA",  "LOGICOP", "DATA", "EXPRESSAOLOGICA"},
{"EXPRESSAOLOGICA",  "/e/"},
{"DATA",  "<num>"},
{"DATA",  "<str>"},
{"DATA",  "<verdadeiro>"},
{"DATA",  "<falso>"},
{"DATA",  "<id>"},
{"LOGICOP",  "<lop|>>"},
{"LOGICOP",  "<lop|>=>"},
{"LOGICOP",  "<lop|<>"},
{"LOGICOP",  "<lop|<=>"},
{"LOGICOP",  "<lop|=>"},
{"LOGICOP",  "<lop|<>>"},
{"LOGICOP",  "<lop|e>"},
{"LOGICOP",  "<lop|ou>"},
{"OP",  "<op|+>"},
{"OP",  "<op|->"},
{"OP",  "<op|*>"},
{"OP",  "<op|/>"},
{"OP",  "<op|mod>"},
{"OP",  "<op|exp>"},
{"OP",  "LOGICOP"}