var followSets = {
	'A': [ '$'],
	'LISTADECLAR': [ '<inicio>'],
	'UNIDECLAR': [ '<var>','<id>','<del|,>','<del|:>','<inicio>'],
	'MULTIDECLAR': [ '<var>','<id>','<del|,>','<del|:>','<inicio>'],
	'TIPO': [ '<var>','<id>','<del|,>','<del|:>','<inicio>'],
	'IDLIST': [ '<del|:>','<del|)>'],
	'CODIGO': [ '<fimalgoritmo>','<senao>','<fimpara>','<fimenquanto>'],
	'COMANDO': [ '<id>','<leia>','<escreva>','<se>','<para>','<enquanto>','<fimalgoritmo>','<senao>','<fimpara>','<fimenquanto>'],
	'PASSO': [ '<faca>'],
	'EXPRESSAO': [ '<id>','<leia>','<escreva>','<se>','<para>','<enquanto>','<fimalgoritmo>','<senao>','<fimpara>','<fimenquanto>'],
	'OPERANDO': [ '<id>','<leia>','<escreva>','<se>','<para>','<enquanto>','<fimalgoritmo>','<senao>','<fimpara>','<fimenquanto>'],
	'STROUT': [ '<del|)>'],
	'PRINTABLE': [ '<id>','<str>','<del|,>','<del|)>'],
	'EXPRESSAOLOGICA': [ '<entao>','<faca>'],
	'DATA': [ '<op|+>','<op|->','<op|*>','<op|/>','<op|mod>','<op|exp>','<lop|>>','<lop|>=>','<lop|<>','<lop|<=>','<lop|=>','<lop|<>>','<lop|e>','<lop|ou>','<id>','<leia>','<escreva>','<se>','<para>','<enquanto>','<fimalgoritmo>','<senao>','<fimpara>','<fimenquanto>','<num>','<str>','<verdadeiro>','<falso>','<entao>','<faca>'],
	'LOGICOP': [ '<num>','<str>','<verdadeiro>','<falso>','<id>'],
	'OP': [ '<num>','<str>','<verdadeiro>','<falso>','<id>'],
  }