var followSets = {
	'A': ['$'],
	'LISTADECLAR': ['<inicio>'],
	'UNIDECLAR': ['<var>', '<id>', '<del|,>', '<del|:>', '<inicio>'],
	'MULTIDECLAR': ['<var>', '<id>', '<del|,>', '<del|:>', '<inicio>'],
	'TIPO': ['<var>', '<id>', '<del|,>', '<del|:>', '<inicio>'],
	'IDLIST': ['<del|:>', '<del|)>'],
	'CODIGO': ['<fimalgoritmo>', '<senao>', '<fimpara>', '<fimenquanto>'],
	'COMANDO': ['<id>', '<leia>', '<escreva>', '<se>', '<para>', '<enquanto>', '<fimalgoritmo>', '<senao>', '<fimpara>', '<fimenquanto>'],
	'PASSO': ['<faca>'],
	'ATRIBUICAO': ['<id>', '<leia>', '<escreva>', '<se>', '<para>', '<enquanto>', '<fimalgoritmo>', '<senao>', '<fimpara>', '<fimenquanto>'],
	'STROUT': ['<del|)>'],
	'PRINTABLE': ['<id>', '<str>', '<del|,>', '<del|)>'],
	'EXPRESSAOLOGICA': ['<entao>', '<faca>'],
	'DATA': ['<num>', '<str>', '<verdadeiro>', '<falso>', '<id>', '<op|+>', '<op|->', '<op|*>', '<op|/>', '<op|mod>', '<op|exp>', '<lop|>>', '<lop|>=>', '<lop|<>', '<lop|<=>', '<lop|=>', '<lop|<>>', '<lop|e>', '<lop|ou>', '<leia>', '<escreva>', '<se>', '<para>', '<enquanto>', '<fimalgoritmo>', '<senao>', '<fimpara>', '<fimenquanto>', '<entao>', '<faca>'],
	'LOGICOP': ['<num>', '<str>', '<verdadeiro>', '<falso>', '<id>'],
	'OP': ['<num>', '<str>', '<verdadeiro>', '<falso>', '<id>'],
}