var gram = {
	1: ['A', '->', '<algoritmo>', '<str>', 'LISTADECLAR', '<inicio>', 'CODIGO', '<fimalgoritmo>'],
	2: ['LISTADECLAR', '->', 'UNIDECLAR', 'LISTADECLAR'],
	3: ['LISTADECLAR', '->', 'MULTIDECLAR', 'LISTADECLAR'],
	4: ['LISTADECLAR', '->', '/e/'],
	5: ['UNIDECLAR', '->', '<var>', '<id>', '<del|:>', 'TIPO'],
	6: ['MULTIDECLAR', '->', 'IDLIST', '<del|:>', 'TIPO'],
	7: ['TIPO', '->', '<inteiro>'],
	8: ['TIPO', '->', '<logico>'],
	9: ['IDLIST', '->', '<id>', 'IDLIST'],
	10: ['IDLIST', '->', '<del|,>', '<id>', 'IDLIST'],
	11: ['IDLIST', '->', '/e/'],
	12: ['CODIGO', '->', 'COMANDO', 'CODIGO'],
	13: ['CODIGO', '->', '/e/'],
	14: ['COMANDO', '->', 'ATRIBUICAO'],
	15: ['COMANDO', '->', '<leia>', '<del|(>', 'IDLIST', '<del|)>'],
	16: ['COMANDO', '->', '<escreva>', '<del|(>', 'STROUT', '<del|)>'],
	17: ['COMANDO', '->', '<se>', 'EXPRESSAOLOGICA', '<entao>', 'CODIGO', '<senao>', 'CODIGO', '<fimse>'],
	18: ['COMANDO', '->', '<para>', '<id>', '<de>', '<num>', '<ate>', '<num>', 'PASSO', '<faca>', 'CODIGO', '<fimpara>'],
	19: ['COMANDO', '->', '<enquanto>', 'EXPRESSAOLOGICA', '<faca>', 'CODIGO', '<fimenquanto>'],
	20: ['PASSO', '->', '<passo>', '<num>'],
	21: ['PASSO', '->', '/e/'],
	22: ['ATRIBUICAO', '->', '<id>', '<op|<->', 'DATA'],
	23: ['ATRIBUICAO', '->', '<id>', '<op|<->', 'EXPRESSAO'],
	24: ['STROUT', '->', '<str>', 'STROUT'],
	25: ['STROUT', '->', '<id>', 'STROUT'],
	26: ['STROUT', '->', '<del|,>', '<id>', 'STROUT'],
	27: ['STROUT', '->', '<del|,>', '<str>', 'STROUT'],
	28: ['STROUT', '->', '/e/'],
	29: ['EXPRESSAOLOGICA', '->', 'EXPRESSAO', 'LOGICOP', 'EXPRESSAO'],
	30: ['DATA', '->', '<num>'],
	31: ['DATA', '->', '<str>'],
	32: ['DATA', '->', '<verdadeiro>'],
	33: ['DATA', '->', '<falso>'],
	34: ['EXPRESSAO', '->', '<id>', 'EXPRESSAO'],
	35: ['EXPRESSAO', '->', 'DATA', 'EXPRESSAO'],
	36: ['EXPRESSAO', '->', 'OP', '<id>', 'EXPRESSAO'],
	37: ['EXPRESSAO', '->', 'OP', 'DATA', 'EXPRESSAO'],
	38: ['EXPRESSAO', '->', '/e/'],
	39: ['LOGICOP', '->', '<lop|>>'],
	40: ['LOGICOP', '->', '<lop|>=>'],
	41: ['LOGICOP', '->', '<lop|<>'],
	42: ['LOGICOP', '->', '<lop|<=>'],
	43: ['LOGICOP', '->', '<lop|=>'],
	44: ['LOGICOP', '->', '<lop|<>>'],
	45: ['LOGICOP', '->', '<lop|e>'],
	46: ['LOGICOP', '->', '<lop|ou>'],
	47: ['OP', '->', '<op|+>'],
	48: ['OP', '->', '<op|->'],
	49: ['OP', '->', '<op|*>'],
	50: ['OP', '->', '<op|/>'],
	51: ['OP', '->', '<op|mod>'],
	52: ['OP', '->', '<op|exp>'],
	53: ['OP', '->', 'LOGICOP']
}