var grammar = {
	1: ['A', '->', '<algoritmo>', '<str>', 'LISTADECLAR', '<inicio>', 'CODIGO', '<fimalgoritmo>', '/e/'],
	2: ['LISTADECLAR', '->', 'UNIDECLAR', 'LISTADECLAR'],
	3: ['LISTADECLAR', '->', 'MULTIDECLAR', 'LISTADECLAR'],
	4: ['LISTADECLAR', '->', '/e/'],
	5: ['UNIDECLAR', '->', '<var>', '<id>', '<del|:>', 'TIPO'],
	6: ['MULTIDECLAR', '->', 'IDLIST', '<del|:>', 'TIPO'],
	7: ['TIPO', '->', '<inteiro>'],
	8: ['TIPO', '->', '<logico>'],
	9: ['IDLIST', '->', '<id>', 'IDLIST'],
	10: ['IDLIST', '->', '<del|,>', '<id>', 'IDLIST'],
	11: ['IDLIST', '->', '/e/'],
	12: ['CODIGO', '->', 'COMANDO', 'CODIGO'],
	13: ['CODIGO', '->', '/e/'],
	14: ['COMANDO', '->', '<id>', '<op|<->', 'EXPRESSAO'],
	15: ['COMANDO', '->', '<leia>', '<del|(>', 'IDLIST', '<del|)>'],
	16: ['COMANDO', '->', '<escreva>', '<del|(>', 'STROUT', '<del|)>'],
	17: ['COMANDO', '->', '<se>', 'EXPRESSAOLOGICA', '<entao>', 'CODIGO', '<senao>', 'CODIGO', '<fimse>', '/e/'],
	18: ['COMANDO', '->', '<para>', '<id>', '<de>', '<num>', '<ate>', '<num>', 'PASSO', '<faca>', 'CODIGO', '<fimpara>', '/e/'],
	19: ['COMANDO', '->', '<enquanto>', 'EXPRESSAOLOGICA', '<faca>', 'CODIGO', '<fimenquanto>', '/e/'],
	20: ['PASSO', '->', '<passo>', '<num>'],
	21: ['PASSO', '->', '/e/'],
	22: ['EXPRESSAO', '->', 'DATA', 'OPERANDO'],
	23: ['OPERANDO', '->', 'OP', 'DATA'],
	24: ['OPERANDO', '->', '/e/'],
	25: ['STROUT', '->', 'PRINTABLE', 'STROUT'],
	26: ['STROUT', '->', '<del|,>', 'PRINTABLE', 'STROUT'],
	27: ['STROUT', '->', '/e/'],
	28: ['PRINTABLE', '->', '<id>'],
	29: ['PRINTABLE', '->', '<str>'],
	30: ['EXPRESSAOLOGICA', '->', 'DATA', 'EXPRESSAOLOGICA'],
	31: ['EXPRESSAOLOGICA', '->', 'LOGICOP', 'DATA', 'EXPRESSAOLOGICA'],
	32: ['EXPRESSAOLOGICA', '->', '/e/'],
	33: ['DATA', '->', '<num>'],
	34: ['DATA', '->', '<str>'],
	35: ['DATA', '->', '<verdadeiro>'],
	36: ['DATA', '->', '<falso>'],
	37: ['DATA', '->', '<id>'],
	38: ['LOGICOP', '->', '<lop|>>'],
	39: ['LOGICOP', '->', '<lop|>=>'],
	40: ['LOGICOP', '->', '<lop|<>'],
	41: ['LOGICOP', '->', '<lop|<=>'],
	42: ['LOGICOP', '->', '<lop|=>'],
	43: ['LOGICOP', '->', '<lop|<>>'],
	44: ['LOGICOP', '->', '<lop|e>'],
	45: ['LOGICOP', '->', '<lop|ou>'],
	46: ['OP', '->', '<op|+>'],
	47: ['OP', '->', '<op|->'],
	48: ['OP', '->', '<op|*>'],
	49: ['OP', '->', '<op|/>'],
	50: ['OP', '->', '<op|mod>'],
	51: ['OP', '->', '<op|exp>'],
	52: ['OP', '->', 'LOGICOP']
}