var table = { A: { '<algoritmo>': 1 },
LISTADECLAR:
 { '<var>': 2,
   '<id>': 3,
   '<del|,>': 3,
   '<del|:>': 3,
   '<inicio>': 4 },
UNIDECLAR: { '<var>': 5 },
MULTIDECLAR: { '<id>': 6, '<del|,>': 6, '/e/': 6 },  TIPO: { '<inteiro>': 7, '<logico>': 8 },
IDLIST: { '<id>': 9, '<del|,>': 10, '<del|:>': 11, '<del|)>': 11 },  CODIGO:
 { '<id>': 12,     '<leia>': 12,
   '<escreva>': 12,
   '<se>': 12,
   '<para>': 12,
   '<enquanto>': 12,
   '<fimalgoritmo>': 13,
   '<senao>': 13,
   '<fimpara>': 13,
   '<fimenquanto>': 13 },
COMANDO:
 { '<id>': 14,
   '<leia>': 15,
   '<escreva>': 16,
   '<se>': 17,
   '<para>': 18,
   '<enquanto>': 19 },
PASSO: { '<passo>': 20, '<faca>': 21 },
STROUT:
 { '<num>': 22,
   '<str>': 22,
   '<verdadeiro>': 22,
   '<falso>': 22,
   '<id>': 22,
   '<del|,>': 23,
   '<del|)>': 24 },
EXPRESSAOLOGICA: { '<id>': 25 },
DATA:
 { '<num>': 26,
   '<str>': 27,
   '<verdadeiro>': 28,
   '<falso>': 29,
   '<id>': 32 },
EXPRESSAO: { '<id>': 33 },
LOGICOP:
 { '<lop|>>': 34,
   '<lop|>=>': 35,
   '<lop|<>': 36,
   '<lop|<=>': 37,
   '<lop|=>': 38,
   '<lop|<>>': 39,
   '<lop|e>': 40,
   '<lop|ou>': 41 },
OP:
 { '<op|+>': 42,
   '<op|->': 43,
   '<op|*>': 44,
   '<op|/>': 45,
   '<op|mod>': 46,
   '<op|exp>': 47,
   '<lop|>>': 48,
   '<lop|>=>': 48,
   '<lop|<>': 48,
   '<lop|<=>': 48,
   '<lop|=>': 48,
   '<lop|<>>': 48,
   '<lop|e>': 48,
   '<lop|ou>': 48 } }