var table = { A: { '<algoritmo>': 1 },
LISTADECLAR:
 { '<var>': 2,
   '<id>': 3,
   '<del|,>': 3,
   '<del|:>': 3,
   '<inicio>': 4 },
UNIDECLAR: { '<var>': 5 },
MULTIDECLAR: { '<id>': 6, '<del|,>': 6, '/e/': 6 },
TIPO: { '<inteiro>': 7, '<logico>': 8 },
IDLIST: { '<id>': 9, '<del|,>': 10, '<del|:>': 11, '<del|)>': 11 },
CODIGO:
 { '<id>': 12,
   '<leia>': 12,
   '<escreva>': 12,
   '<se>': 12,
   '<para>': 12,
   '<enquanto>': 12,
   '<fimalgoritmo>': 13,
   '<senao>': 13,
   '<fimpara>': 13,
   '<fimenquanto>': 13 },
COMANDO:
 { '<id>': 14,
   '<leia>': 15,
   '<escreva>': 16,
   '<se>': 17,
   '<para>': 18,
   '<enquanto>': 19 },
PASSO: { '<passo>': 20, '<faca>': 21 },
ATRIBUICAO:
 { '<num>': 22,
   '<str>': 22,
   '<verdadeiro>': 22,
   '<falso>': 22,
   '<id>': 24,
   '<op|+>': 23,
   '<op|->': 23,
   '<op|*>': 23,
   '<op|/>': 23,
   '<op|mod>': 23,
   '<op|exp>': 23,
   '<lop|>>': 23,
   '<lop|>=>': 23,
   '<lop|<>': 23,
   '<lop|<=>': 23,
   '<lop|=>': 23,
   '<lop|<>>': 23,
   '<lop|e>': 23,
   '<lop|ou>': 23,
   '<leia>': 24,
   '<escreva>': 24,
   '<se>': 24,
   '<para>': 24,
   '<enquanto>': 24,
   '<fimalgoritmo>': 24,
   '<senao>': 24,
   '<fimpara>': 24,
   '<fimenquanto>': 24 },
STROUT: { '<id>': 25, '<str>': 25, '<del|,>': 26, '<del|)>': 27 },
PRINTABLE: { '<id>': 28, '<str>': 29 },
EXPRESSAOLOGICA:
 { '<num>': 30,
   '<str>': 30,
   '<verdadeiro>': 30,
   '<falso>': 30,
   '<id>': 30,
   '<lop|>>': 31,
   '<lop|>=>': 31,
   '<lop|<>': 31,
   '<lop|<=>': 31,
   '<lop|=>': 31,
   '<lop|<>>': 31,
   '<lop|e>': 31,
   '<lop|ou>': 31,
   '<entao>': 32,
   '<faca>': 32 },
DATA:
 { '<num>': 33,
   '<str>': 34,
   '<verdadeiro>': 35,
   '<falso>': 36,
   '<id>': 37 },
LOGICOP:
 { '<lop|>>': 38,
   '<lop|>=>': 39,
   '<lop|<>': 40,
   '<lop|<=>': 41,
   '<lop|=>': 42,
   '<lop|<>>': 43,
   '<lop|e>': 44,
   '<lop|ou>': 45 },
OP:
 { '<op|+>': 46,
   '<op|->': 47,
   '<op|*>': 48,
   '<op|/>': 49,
   '<op|mod>': 50,
   '<op|exp>': 51,
   '<lop|>>': 52,
   '<lop|>=>': 52,
   '<lop|<>': 52,
   '<lop|<=>': 52,
   '<lop|=>': 52,
   '<lop|<>>': 52,
   '<lop|e>': 52,
   '<lop|ou>': 52 } }